<?php

return [
    'en' => ['name' => 'English'],
    'es' => ['name' => 'Spanish'],
    'fr' => ['name' => 'French'],
    'de' => ['name' => 'German'],
    'it' => ['name' => 'Italian'],
    'pt' => ['name' => 'Portuguese'],
    'ru' => ['name' => 'Russian'],
    'ja' => ['name' => 'Japanese'],
    'ko' => ['name' => 'Korean'],
    'zh' => ['name' => 'Chinese (Simplified)'],
    'zh-TW' => ['name' => 'Chinese (Traditional)'],
    'ar' => ['name' => 'Arabic'],
    'hi' => ['name' => 'Hindi'],
    'bn' => ['name' => 'Bengali'],
    'pa' => ['name' => 'Punjabi'],
    'te' => ['name' => 'Telugu'],
    'mr' => ['name' => 'Marathi'],
    'ta' => ['name' => 'Tamil'],
    'gu' => ['name' => 'Gujarati'],
    'kn' => ['name' => 'Kannada'],
    'ml' => ['name' => 'Malayalam'],
    'th' => ['name' => 'Thai'],
    'vi' => ['name' => 'Vietnamese'],
    'id' => ['name' => 'Indonesian'],
    'tr' => ['name' => 'Turkish'],
    'pl' => ['name' => 'Polish'],
    'uk' => ['name' => 'Ukrainian'],
    'nl' => ['name' => 'Dutch'],
    'sv' => ['name' => 'Swedish'],
    'da' => ['name' => 'Danish'],
    'no' => ['name' => 'Norwegian'],
    'fi' => ['name' => 'Finnish'],
    'hu' => ['name' => 'Hungarian'],
    'cs' => ['name' => 'Czech'],
    'ro' => ['name' => 'Romanian'],
    'gr' => ['name' => 'Greek'],
    'he' => ['name' => 'Hebrew'],
    'fa' => ['name' => 'Persian'],
    'ur' => ['name' => 'Urdu'],
    'my' => ['name' => 'Burmese'],
    'km' => ['name' => 'Khmer'],
    'lo' => ['name' => 'Lao'],
    'ms' => ['name' => 'Malay'],
    'tl' => ['name' => 'Tagalog'],
    'bg' => ['name' => 'Bulgarian'],
    'hr' => ['name' => 'Croatian'],
    'sr' => ['name' => 'Serbian'],
    'sk' => ['name' => 'Slovak'],
    'sl' => ['name' => 'Slovenian'],
];
